### ISSUE TITLE
No module named 'scipdf'

### ISSUE THREAD

**Issue by Xh-xie** [Raychanan/ChatGPT-for-Translation#11]
Traceback (most recent call last):
  File "C:\Users\***\ChatGPT-for-Translation\ChatGPT-translate.py", line 182, in <module>
    from utils.parse_pdfs.extract_pdfs import process_pdfs
  File "C:\Users\***\ChatGPT-for-Translation\utils\parse_pdfs\extract_pdfs.py", line 4, in <module>
    import scipdf
ModuleNotFoundError: No module named 'scipdf'
需要部署scipdf项目服务器吗？

**Comment by laoliloal** [comment]
Same problem encountered in Colab env, and this have been continued several days. My solution is to rollback version using the command: 
`! git checkout 42bc95e6fae5b8c2b771ba202feb4081e3cd69db`

**Comment by Raychanan** [comment]
Thanks for pointing this out.

It seems that the code was functioning properly on my local machine but not on Google Colab. I made some changes to how scipdf is imported and now there are no reported issues on Google Colab.

Try again and inform me if the bug still persists.

感谢指出这个问题。看起来代码在我的本地机器上运行正常，但在Google Colab上却不是。我对scipdf的导入方式进行了一些更改，现在在Google Colab上没有报告任何问题。再试一次，并告诉我是否仍然存在错误。

**Comment by laoliloal** [comment]
Seems work well now. Thanks a lot for your update!

**Comment by Xh-xie** [comment]
测试时报错。
/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2023-03-29 04:47:45.375346: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-29 04:47:46.881402: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-29 04:47:46.881581: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-29 04:47:46.881613: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-29 04:47:48.621306: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
/content/ChatGPT-for-Translation/utils/parse_pdfs/scipdf/pdf/parse_pdf.py:149: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if middlename is not "":
/content/ChatGPT-for-Translation/utils/parse_pdfs/scipdf/pdf/parse_pdf.py:236: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if heading is not "" or text is not "":
/content/ChatGPT-for-Translation/utils/parse_pdfs/scipdf/pdf/parse_pdf.py:236: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if heading is not "" or text is not "":
/content/ChatGPT-for-Translation/utils/parse_pdfs/scipdf/pdf/parse_pdf.py:264: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if journal is "":
/content/ChatGPT-for-Translation/utils/parse_pdfs/scipdf/pdf/parse_pdf.py:277: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if middlename is not "":
/content/ChatGPT-for-Translation/utils/parse_pdfs/scipdf/pdf/parse_pdf.py:326: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if formula_coordinates is not "":
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
File extension  is not allowed.
Traceback (most recent call last):
  File "/content/ChatGPT-for-Translation/ChatGPT-translate.py", line 347, in <module>
    main()
  File "/content/ChatGPT-for-Translation/ChatGPT-translate.py", line 343, in main
    process_file(input_path, options)
  File "/content/ChatGPT-for-Translation/ChatGPT-translate.py", line 307, in process_file
    if not check_file_path(file_path, options):
  File "/content/ChatGPT-for-Translation/ChatGPT-translate.py", line 276, in check_file_path
    raise Exception("Please use a txt file or URL")
Exception: Please use a txt file or URL(url)
![image](https://user-images.githubusercontent.com/128797899/228430585-9663fc07-e304-4d24-90d8-f56c81cecc81.png)
