### ISSUE TITLE
Failed to extract xx.pdf: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by yefeiyu** [Raychanan/ChatGPT-for-Translation#26]
0%|                                                                                                                      | 0/1 [00:00<?, ?it/s]Error: 500
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.28s/it]Failed to extract abcdys.pdf: object of type 'NoneType' has no len()
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.28s/it]

Here are PDFs without extracted txt files. You want to make sure 1. these files are OCRed 2. They are not corrupted:
abcdys
Traceback (most recent call last):
  File "/Users/charlesthomas/gh/ChatGPT-for-Translation/ChatGPT-translate.py", line 356, in <module>
    main()
  File "/Users/charlesthomas/gh/ChatGPT-for-Translation/ChatGPT-translate.py", line 352, in main
    process_file(input_path, options)
  File "/Users/charlesthomas/gh/ChatGPT-for-Translation/ChatGPT-translate.py", line 319, in process_file
    translate_text_file(str(file_path), options)
  File "/Users/charlesthomas/gh/ChatGPT-for-Translation/ChatGPT-translate.py", line 105, in translate_text_file
    paragraphs = read_and_preprocess_data(text_filepath_or_url, options)
  File "/Users/charlesthomas/gh/ChatGPT-for-Translation/ChatGPT-translate.py", line 194, in read_and_preprocess_data
    with open(text_filepath_or_url, "r", encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './abcdys_extracted.txt'

**Comment by yefeiyu** [comment]
该问题已解决。
原因是pdf加密了，该pdf无法复制、转换。复制的所有内容都是乱码。
