### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\xe5' in position 4315: illegal multibyte sequence

### ISSUE THREAD

**Issue by RedCatJump** [Raychanan/ChatGPT-for-Translation#3]
Translating paragraph pairs: 100%|███████████████████████████████████████| 722/722 [05:26<00:00,  2.21paragraph pair/s]
Traceback (most recent call last):
  File "C:\Users\liu-pc\ChatGPT-for-Translation\ChatGPT-translate.py", line 240, in <module>
    main()
  File "C:\Users\liu-pc\ChatGPT-for-Translation\ChatGPT-translate.py", line 236, in main
    process_file(input_path, options)
  File "C:\Users\liu-pc\ChatGPT-for-Translation\ChatGPT-translate.py", line 213, in process_file
    translate_text_file(str(file_path), options)
  File "C:\Users\liu-pc\ChatGPT-for-Translation\ChatGPT-translate.py", line 136, in translate_text_file
    f.write(translated_text)
UnicodeEncodeError: 'gbk' codec can't encode character '\xe5' in position 4315: illegal multibyte sequence

**Comment by Raychanan** [comment]
I have looked into the matter and made the necessary changes to the way data is imported.
