### ISSUE TITLE
UnboundLocalError: local variable 'ref_paragraphs' referenced before assignment

### ISSUE THREAD

**Issue by JesseHYW** [Raychanan/ChatGPT-for-Translation#4]
Translating input.txt...
Translating paragraphs: 100%|█████████████████████████████████████████████████████| 5/5 [00:11<00:00,  2.40s/paragraph]
Traceback (most recent call last):
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 330, in <module>
    main()
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 326, in main
    process_file(input_path, options)
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 293, in process_file
    translate_text_file(str(file_path), options)
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 136, in translate_text_file
    translated_text += "\n" + "\n".join(ref_paragraphs)
UnboundLocalError: local variable 'ref_paragraphs' referenced before assignment

**Comment by Raychanan** [comment]
Fixed. Try again and let me know it still does not work on your end.

**Comment by JesseHYW** [comment]
Cool, indeed fixed.
