### ISSUE TITLE
翻译PDF文件时出现报错

### ISSUE THREAD

**Issue by kunflow** [Raychanan/ChatGPT-for-Translation#47]
在执行以下命令时出现报错
python ChatGPT-translate.py --input_path=.\tests\sample.pdf --openai_key=xxxxxxxxx
Translating tests\sample.pdf...
Extracting text from PDF file...
Error: 503
Traceback (most recent call last):
  File "C:\ChatGPT-for-Translation\ChatGPT-translate.py", line 308, in <module>
    main()
  File "C:\ChatGPT-for-Translation\ChatGPT-translate.py", line 304, in main
    process_file(input_path, options)
  File "C:\ChatGPT-for-Translation\ChatGPT-translate.py", line 271, in process_file
    translate_text_file(str(file_path), options)
  File "C:\ChatGPT-for-Translation\ChatGPT-translate.py", line 93, in translate_text_file
    paragraphs = read_and_preprocess_data(text_filepath_or_url, options)
  File "C:\ChatGPT-for-Translation\ChatGPT-translate.py", line 175, in read_and_preprocess_data
    with open(text_filepath_or_url, "r", encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tests/sample_extracted.txt'

在ubuntu服务器上也是同样的错误，使用https://colab.research.google.com/drive/1_715zHeS3VaZaB9ISyo29Zp-KOTsyP8D 翻译pdf文件时，出现了同样的报错信息。

**Comment by Raychanan** [comment]
我重新跑了一遍，colab 上没有出现问题。

你首先要确保你使用的 PDF 的确能在自己的电脑上能够提取出文字

**Comment by kunflow** [comment]
使用的git clone下来的tests目录下自带的pdf文档，不管在linux服务器，还是在windows电脑上，或者在macos系统上，都是报相同的错误，可以提供一下依赖包的版本吗？我想在本地运行该项目，但是在使用pip install -r requirements,txt安装依赖包后，还提示缺少translate包？
