### ISSUE TITLE
When translating into German

### ISSUE THREAD

**Issue by JesseHYW** [Raychanan/ChatGPT-for-Translation#5]
Traceback (most recent call last):
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 334, in <module>
    main()
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 330, in main
    process_file(input_path, options)
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 297, in process_file
    translate_text_file(str(file_path), options)
  File "D:\EdgeDownload\ChatGPT-for-Translation\ChatGPT-translate.py", line 143, in translate_text_file
    f.write(translated_text)
UnicodeEncodeError: 'gbk' codec can't encode character '\xe4' in position 469: illegal multibyte sequence

**Comment by Raychanan** [comment]
I have never encountered this issue on my Mac or Google Colab. It appears to be a singular problem on Windows. I specified the encoding when writing the file, but I am uncertain if it will work for you. Try again and inform me if the issue persists. Otherwise, providing some parts of your text files would be helpful for me to figure out the issue.
